# remove it if you don't want to force ssl
FORCE_SSL: 'true'

SECRET_KEY_BASE: "08b7a7ae2d0446f1c434af0a57585d67c015a75ebff30118c720f1d59f04bfcf273a53a86dd44045e629fec9b2f556019c10485caa4e660d68b796b715de4a12"

FACEBOOK_APP_ID: ""
GOOGLE_APP_ID: ""
TWITTER_APP_ID: ""
MEETUP_APP_ID: ""
LINKEDIN_APP_ID: ""
PARMA_APP_ID: ""
TECNOLOGIEDEMOCRATICHE_APP_ID: ''

MAPS_API_KEY: ""

GOOGLE_ANALYTICS_ID: "YOUR GOOGLE ANALYTICS ID"

FACEBOOK_APP_SECRET: ""
GOOGLE_APP_SECRET: ""
TWITTER_APP_SECRET: ""
MEETUP_APP_SECRET: ""
LINKEDIN_APP_SECRET: ""
PARMA_APP_SECRET: ""
TECNOLOGIEDEMOCRATICHE_APP_SECRET: ''

TECNOLOGIEDEMOCRATICHE_APP_URL: "https://tecnologiedemocratiche.herokuapp.com/"

RECAPTCHA_PUBLIC: ""
RECAPTCHA_PRIVATE: ""

GEOSPATIAL_NAME: ""

#####################
#email service
#####################

EMAIL_ADDRESS: ""
EMAIL_USERNAME: ""
EMAIL_PASSWORD: ""

MAILER_DEFAULT_HOST: "www.airesis.eu"

# set your email address to override email receiver in development and test
OVERRIDE_MAIL_RECIPIENT: ""

#####################
#newsletter parameters
#####################

NEWSLETTER_FROM_ADDRESS: ""
NEWSLETTER_TWITTER_URL: ""
NEWSLETTER_FACEBOOK_URL: ""
NEWSLETTER_GOOGLEPLUS_URL: ""
NEWSLETTER_PREFERENCES_URL: ""
NEWSLETTER_HOME_URL: ""

#####################
# feedbacks (optional)
# set these values to send and receive feedbacks from users
#####################
FEEDBACK_SENDER: "Feedback <feedback@example.com>"
FEEDBACK_RECEIVER: "help@example.com"

#####################
# email settings (required)
# email addresses for all email services
#####################
DEFAULT_FROM: "App <info@example.com>"
NOREPLY_EMAIL: "No Reply <noreply@example.com>"

#####################
#redmine integration (optional)
#####################

BUGTRACKING_URL: ""
BUGTRACKING_USERNAME: ""
BUGTRACKING_PASSWORD: ""

#####################
#application parameters
#####################

APP_SHORT_NAME: "Airesis"
APP_LONG_NAME: "Airesis - Scegli di partecipare"
APP_EMAIL_ADDRESS: "info@example.com"
SITE: "http://www.airesis.eu"
ADMIN_EMAIL: "youremail@example.com"
ADMIN_PASSWORD: "password"

DEVISE_SECRET_KEY: ""

REDIS_URL: "redis://127.0.0.1:6379/12"

# remove this variable if you are not using amazon s3
AWS_HOST: "s3-eu-west-1.amazonaws.com"
AWS_BUCKET: ""
AWS_ACCESS_KEY_ID: ""
AWS_SECRET_ACCESS_KEY: ""

# assets on a cdn. remove it if you are not using a cdn
ASSETS_HOST: ""

# remove this variable if you are not using cloudfront. set it to cloudfront alias if you want to you it
AWS_ALIAS: "static.yourwebsite.com"


# Newrelic
NEW_RELIC_LICENSE_KEY: 'FROM NEW RELCI'
NEW_RELIC_APP_NAME: 'YOUR NEW RELIC APP NAME'

#####################
#crowdin integration (optional)
#####################

CROWDIN_API: ""
CROWDIN_PROJECT_ID: ""
CROWDIN_ACCOUNT_KEY: ""

#####################
#capistrano settings (optional)
#####################

CAP_STAGING_USER: ""
CAP_STAGING_SERVER: ""


##############
#sentry settings. remove these keys to not use it (leaving them empty will throw an error)
#############

SENTRY_PUBLIC_KEY: ""
SENTRY_PRIVATE_KEY: ""
SENTRY_PORT: ""

#############
# environment constants (leave default values for default behaviour, change them to change platform behaviour)
# the values are the ones used on airesis official installation
#############

#percentage of active users on the platform. this number is used to calculate quorums in the open space only
#the calculation is quorum.percentage * (users * ACTIVE_USER_PERCENTAGE)
#if you have 100 registered users and a 50% quorum the number of valutations and votes is 50 (0.5 * (100 * 1)).
#if you change this value to 30, then the number of valutations and votes will be 15 (0.5 * (100 * 0.3)).
#if you change this value to 10, then the number of valutations and votes will be 5 (0.5 * (100 * 0.1)).
#this is useful to provide accessible quorums in the open space. maybe one day will not be necessary
#allow integers, required
ACTIVE_USERS_PERCENTAGE: "100"

#this is the maximum length for a contribute or a comment in proposals or blog
#allow integers, required
CONTRIBUTE_MAX_LENGTH: "2200"

#minimum amount of marks for a contribute to be eligible for deletion
CONTRIBUTE_MARKS: "3"

#minimum amount of time between the end of debate and the beginning of vote. please do not set it below few minutes.
#must be specified in minutes
DEBATE_VOTE_DIFFERENCE: "10"

#max number of comments per page
COMMENTS_PER_PAGE: "5"
#max number of proposals per page
PROPOSALS_PER_PAGE: "10"

#max number of topics per page
TOPICS_PER_PAGE: "10"

#contributes and comments are limited for each user?
LIMIT_COMMENTS: "false"

#if contributes and comments are limited this is the minimum amount of time between two subsequent comments from the same user
#must be specified in seconds
COMMENTS_TIME_LIMIT: "30"

#proposals are limited for each user?
LIMIT_PROPOSALS: "false"

#if proposals are limited this is the minimum amount of time between two subsequent proposals from the same user
#must be defined in seconds
PROPOSALS_TIME_LIMIT: "60"

#groups creation is limited?
LIMIT_GROUPS: "true"

#if groups creation is limited this is the minimum amount of time between two subsequent creations from the same user
#must be specified in hours
GROUPS_TIME_LIMIT: "24"

#if you are using tokens for voting yoy may need to set a drift for token creation.
#must be specified in seconds
ROTP_DRIFT: "20"

#default options when for groups when created.
#the owner of the group can always change them after he created the group but the 90% of users will
#use default values so it makes the difference

#can users of a group change the settings of a proposal when it's created?
#default is false: it means that the proposals settings will be selected by the group administrator
#allow true,TRUE,false,FALSE, required
DEFAULT_CHANGE_ADVANCED_OPTIONS: "false"

#the discussion is anonimous?
#default is true: it means that the proposal's discussion will be anonimous
#allow true,TRUE,false,FALSE, required
DEFAULT_ANONIMA: "true"

#actions enabled by default for users when they join a group. Look at GroupAction model to see available values.
#expert variable, don't touch it if you don't know what are you going to do
DEFAULT_GROUP_ACTIONS: "1, 2, 6, 7, 8, 9, 11, 12"

#actions enabled by default for users when they join a group area. Look at GroupAction model to see available values
#expert variable, don't touch it if you don't know what are you going to do
DEFAULT_AREA_ACTIONS: "6, 7, 8, 11, 12"

#after this number of days, if the author has not chose a voting date, the users which have the right to choose a vote day, can do it
OTHERS_CHOOSE_VOTE_DATE_DAYS: "5"

### PAYPAL CONFIGURATION ###

PAYPAL_MERCHANT: "X25TSHNPP9XXX"
#test
PAYPAL_URL: "https://www.sandbox.paypal.com/cgi-bin/webscr"
#production:
#PAYPAL_URL: "https://www.paypal.com/cgi-bin/webscr"
