development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://localhost:9292/faye/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye/faye"
  secret_token: "secret"
staging:
  server: "http://localhost:9292/faye/faye"
  secret_token: "secret"
