theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
#theme_advanced_buttons1: bold,italic,underline
#theme_advanced_buttons2:
#theme_advanced_buttons3:

#theme_advanced_statusbar_location: bottom
#theme_advanced_buttons3_add:
#  - tablecontrols
#  - fullscreen
#plugins:
#  - table
#  - fullscreen